### ISSUE TITLE
[Bug] Issue with Polling Updates

### ISSUE THREAD

**Issue by illuzn** [Apoc182/local_daikin#31]
# Bug

There is an issue with the manner in which the code polls for updates.

# Replication Steps

1. Turn on the air conditioning using the daikin app or the remote.
2. Wait.
3. The entity in Home Assistant never updates.

# Potential Causes/ Diagnosis

I think the code might be using a deprecated polling method or some such but I'm a complete novice at Python.

The relevant documentation reference is here:
https://developers.home-assistant.io/docs/integration_fetching_data/

Manually running an update using the developer tools as follows works:

```yaml
action: homeassistant.update_entity
data:
  entity_id:
    - climate.local_daikin

```

A further example can be found here:

https://github.com/ludeeus/integration_blueprint/blob/main/custom_components/integration_blueprint/coordinator.py
