### ISSUE TITLE
Multiple units

### ISSUE THREAD

**Issue by ajvandr** [Apoc182/local_daikin#6]
I may just be a potato, but is there a way to use this for multiple units?
I have a FTXM35YVMA and a FTXM25YVMA and this works with either of them, but if I configure two entries in the config the second is ignored.

**Comment by Apoc182** [comment]
Hi @ajvandr 

Try this new version and pass your IP addresses like so:

```
climate:
  - platform: local_daikin
    ip_address: 
      - 192.168.1.69
      - 192.168.1.70
```

I only have the one so i am unable to test, but working with my single one.
```
